enum ACTION_TYPES {
  ADD_BIBLE_FAVORITE = 'ACTION_ADD_BIBLE_FAVORITE',

  FETCH_BIBLE = 'ACTION_FETCH_BIBLE',
  FETCH_BIBLE_SUCCESS = 'ACTION_FETCH_BIBLE_SUCCESS',
  FETCH_BIBLE_FAILURE = 'ACTION_FETCH_BIBLE_FAILURE',
}

export default ACTION_TYPES;
